# Generated by Django 5.0.6 on 2024-06-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('title', models.TextField()),
                ('descr', models.TextField()),
                ('file', models.FileField(upload_to='static/uploads/videos/')),
            ],
        ),
    ]
