# Generated by Django 4.1 on 2022-09-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEscalations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=5)),
                ('issue', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskHD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_uni', models.TextField(unique=True)),
                ('type', models.TextField()),
                ('ref', models.TextField()),
                ('owner', models.IntegerField(default=0)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_uni', models.TextField()),
                ('tran_title', models.TextField()),
                ('tran_descr', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('owner', models.IntegerField(default=0)),
            ],
        ),
    ]
