# Generated by Django 4.1.6 on 2024-07-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_bulksms_file_alter_contacts_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2024-07-04_15-42-37'),
        ),
    ]
