# Generated by Django 3.2.13 on 2022-08-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_pendingescalations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingescalations',
            name='issue',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
