# Generated by Django 4.1.6 on 2024-07-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_bulksms_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='type',
            field=models.CharField(default='retail', max_length=10),
        ),
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2024-07-04_16-58-06'),
        ),
    ]
