# Generated by Django 4.1.6 on 2023-08-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_tasktransactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskTransactions',
        ),
    ]
