# Generated by Django 4.1 on 2022-09-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='domain',
            field=models.TextField(default='OTH'),
        ),
        migrations.AddField(
            model_name='tags',
            name='provider',
            field=models.IntegerField(default=0),
        ),
    ]
