# Generated by Django 3.2.13 on 2022-08-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_tags_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=models.TextField(default='OTH'),
        ),
    ]
