# Generated by Django 3.2.13 on 2022-08-14 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_questions_uni'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.questions')),
            ],
        ),
    ]
