# Generated by Django 3.2.13 on 2022-08-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_questiontags_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(to='community.QuestionTags'),
        ),
    ]
