# Generated by Django 4.1 on 2022-09-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_taskhd_tasktrans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhd',
            name='entry_uni',
            field=models.TextField(unique=True),
        ),
    ]
