# Generated by Django 4.1 on 2022-09-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_taskhd_entry_uni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskHD',
        ),
        migrations.DeleteModel(
            name='TaskTrans',
        ),
    ]
