# Generated by Django 3.2.13 on 2022-08-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_questions_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='tags',
        ),
        migrations.AddField(
            model_name='questions',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
