# Generated by Django 3.2.13 on 2022-08-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
