# Generated by Django 3.2.13 on 2022-08-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_answers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.TextField(),
        ),
    ]
