# Generated by Django 3.2.13 on 2022-08-14 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_alter_answers_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
