# Generated by Django 3.2.13 on 2022-08-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_answers_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('user', models.IntegerField(default=0)),
            ],
        ),
    ]
