# Generated by Django 4.1 on 2022-08-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article_meta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
                ('owner', models.CharField(default='anton', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('article', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('intro', models.TextField(default='none')),
                ('meta', models.CharField(default='none', max_length=200)),
                ('image', models.ImageField(default='1.jpg', upload_to='static/blog/asssets/article/')),
            ],
        ),
        migrations.CreateModel(
            name='userAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=1000)),
                ('token', models.TextField(max_length=1000)),
                ('meta_words', models.TextField(max_length=1000)),
            ],
        ),
    ]
