# Generated by Django 3.2.10 on 2022-03-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('article', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('meta', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
