# Generated by Django 3.2.13 on 2022-08-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('descr', models.TextField()),
                ('mobile', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
