# Generated by Django 4.1 on 2022-09-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField()),
                ('sent_from', models.IntegerField()),
                ('message', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(max_length=3)),
                ('descr', models.TextField()),
                ('mobile', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='static/blog/asssets/article/2022-09-05/'),
        ),
    ]
