# Generated by Django 4.0.3 on 2022-03-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_meta',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
