# Generated by Django 3.2.13 on 2022-08-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_providers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providers',
            old_name='code',
            new_name='provider_code',
        ),
    ]
