# Generated by Django 3.2.13 on 2022-08-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_providers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField()),
                ('sent_from', models.IntegerField()),
                ('message', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
