# Generated by Django 3.2.10 on 2022-03-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220331_0430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='meta',
            new_name='article_meta',
        )
    ]
