# Generated by Django 3.2.10 on 2022-03-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220331_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='asssets/'),
        )
    ]
