# Generated by Django 3.2.13 on 2022-09-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlechat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='static/blog/asssets/article/2022-09-01/'),
        ),
    ]
