# Generated by Django 3.2.10 on 2022-03-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220331_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='static/blog/asssets/article/'),
        ),
    ]
