# Generated by Django 4.1 on 2022-09-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='static/blog/asssets/article/2022-09-04/'),
        ),
    ]
