# Generated by Django 4.1 on 2022-09-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_articles_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Providers',
        ),
    ]
