# Generated by Django 4.1 on 2022-09-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_providers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(max_length=3)),
                ('descr', models.TextField()),
                ('mobile', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
