# Generated by Django 5.0.6 on 2024-06-13 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField()),
                ('type', models.IntegerField(default=0)),
                ('descr', models.TextField()),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('model', models.TextField()),
                ('manufacturer', models.TextField()),
                ('storage', models.TextField()),
                ('memory', models.TextField()),
                ('processor', models.TextField()),
                ('details', models.TextField()),
                ('image', models.FileField(default='static/general/img/products/asset.png', upload_to='static/uploads/ccms_inv/products/')),
                ('tags', models.TextField(default='NULL')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.assetgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_type', models.CharField(max_length=255)),
                ('ram_size', models.PositiveIntegerField()),
                ('cpu', models.CharField(max_length=255)),
                ('storage_type', models.CharField(max_length=255)),
                ('storage_size', models.CharField(max_length=255)),
                ('used_storage', models.CharField(max_length=255)),
                ('remaining_storage', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255, unique=True)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('printer', models.TextField()),
                ('logged_on_user', models.CharField(max_length=255)),
                ('computer_name', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('updated_time', models.TimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.computergroup')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerMoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor', models.TextField()),
                ('keyword', models.TextField()),
                ('mouse', models.TextField()),
                ('ups', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('updated_time', models.TimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('computer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.computer')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.department')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('loged_on', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.computer')),
            ],
        ),
        migrations.CreateModel(
            name='DocAppr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.TextField()),
                ('doc_type', models.TextField()),
                ('approved_on', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrnHd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('ref', models.TextField()),
                ('entry_no', models.TextField()),
                ('remark', models.TextField()),
                ('taxable', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.locations')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.suppmaster')),
            ],
        ),
        migrations.CreateModel(
            name='GrnTran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('pack_qty', models.TextField()),
                ('qty', models.DecimalField(decimal_places=2, max_digits=65)),
                ('total_qty', models.IntegerField()),
                ('un_cost', models.DecimalField(decimal_places=2, max_digits=60)),
                ('tot_cost', models.DecimalField(decimal_places=2, max_digits=60)),
                ('entry_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.grnhd')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.productpacking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.productmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PoHd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.TextField()),
                ('remark', models.TextField()),
                ('taxable', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('open', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.locations')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.suppmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PoTran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('packing', models.TextField()),
                ('pack_qty', models.DecimalField(decimal_places=2, max_digits=65)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=65)),
                ('total_qty', models.IntegerField()),
                ('un_cost', models.DecimalField(decimal_places=2, max_digits=60)),
                ('tot_cost', models.DecimalField(decimal_places=2, max_digits=60)),
                ('entry_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pohd')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.productmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PriceCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=60)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.productmaster')),
            ],
        ),
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer', models.TextField(default='NULL')),
                ('ups', models.TextField(default='NULL')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_kb', to='inventory.assets')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_moni', to='inventory.assets')),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_mouse', to='inventory.assets')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.unitmembers')),
                ('sys_uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_sys_uni', to='inventory.assets')),
            ],
        ),
    ]
