# Generated by Django 4.1 on 2022-11-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_pricecenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potran',
            old_name='quantity',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='potran',
            old_name='total',
            new_name='total_qty',
        ),
        migrations.AddField(
            model_name='potran',
            name='tot_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potran',
            name='un_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=60),
            preserve_default=False,
        ),
    ]
