# Generated by Django 4.1 on 2022-11-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_quantity_potran_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pohd',
            name='taxable',
            field=models.IntegerField(default=1),
        ),
    ]
