# Generated by Django 4.1 on 2022-11-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_pohd_created_by'),
    ]

    operations = [

        migrations.AddField(
            model_name='pohd',
            name='approved_date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pohd',
            name='approved_time',
            field=models.TimeField(),
            preserve_default=False,
        ),
    ]
