# Generated by Django 4.1.6 on 2023-10-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_departmentreportmailque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentreportmailque',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
