# Generated by Django 4.1 on 2022-11-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingparticipant',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='name',
        ),
    ]
