# Generated by Django 4.1 on 2022-11-16 01:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_rename_owner_meetingparticipant_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtrans',
            name='title',
        ),
        migrations.AddField(
            model_name='meetingtrans',
            name='talking_point',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='meeting.meetingtalkingpoints'),
            preserve_default=False,
        ),
    ]
