# Generated by Django 4.1 on 2022-11-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_remove_meetingtrans_title_meetingtrans_talking_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingTrans',
        ),
    ]
