# Generated by Django 4.1.6 on 2023-09-08 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0137_alter_bulksms_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('pword', models.CharField(max_length=4)),
                ('img', models.ImageField(upload_to='static/general/clerks/')),
                ('flag_dwn', models.IntegerField(default=1)),
                ('flag_disable', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.locations')),
            ],
        ),
    ]
