# Generated by Django 3.2.13 on 2022-09-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('title', models.TextField()),
                ('descr', models.TextField()),
                ('image', models.FileField(upload_to='static/general/videos/2022-09-01/')),
            ],
        ),
    ]
