# Generated by Django 3.2.13 on 2022-09-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_rename_image_videos_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='uploaded_on',
            field=models.DateField(auto_now=True),
        ),
    ]
