# Generated by Django 4.1.6 on 2023-06-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='icon',
            field=models.FileField(default=1, upload_to='static/files/2023-06-01_14-25-00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='root',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
