# Generated by Django 4.1.6 on 2024-07-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='file',
            field=models.FileField(upload_to='static/uploads/apps/2024-07-04_15-42-37'),
        ),
    ]
