# Generated by Django 4.1.6 on 2023-06-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0002_app_icon_app_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.FileField(upload_to='static/files/2023-06-01_14-31-44'),
        ),
    ]
