# Generated by Django 4.1.6 on 2023-06-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0003_app_version_alter_app_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.FileField(upload_to='static/files/2023-06-01_14-38-53'),
        ),
        migrations.CreateModel(
            name='VersionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('version_no', models.IntegerField()),
                ('files', models.FileField(upload_to='static/appversion')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appscenter.app')),
            ],
        ),
    ]
