# Generated by Django 4.1.6 on 2023-06-01 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_computer_mac_address'),
        ('appscenter', '0004_alter_app_icon_versioncontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.FileField(upload_to='static/files/2023-06-01_16-00-49'),
        ),
        migrations.CreateModel(
            name='AppAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appscenter.app')),
                ('mach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.computer')),
            ],
        ),
    ]
