# Generated by Django 4.1.6 on 2023-06-02 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0005_alter_app_icon_appassign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appassign',
            name='status',
        ),
        migrations.AddField(
            model_name='appassign',
            name='updated_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appassign',
            name='updated_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appassign',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.FileField(upload_to='static/files/2023-06-02_05-50-34'),
        ),
        migrations.AlterField(
            model_name='appassign',
            name='created_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
