# Generated by Django 4.1.6 on 2023-06-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0007_alter_app_icon_alter_versioncontrol_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.FileField(upload_to='static/files/2023-06-13_11-58-29'),
        ),
    ]
