# Generated by Django 4.1.6 on 2023-06-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_computer_group'),
        ('appscenter', '0009_alter_app_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.FileField(upload_to='static/files/2023-06-13_12-01-32'),
        ),
        migrations.CreateModel(
            name='AppContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('computers', models.ManyToManyField(to='inventory.computergroup')),
            ],
        ),
    ]
