# Generated by Django 4.1.6 on 2023-06-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_computer_group'),
        ('appscenter', '0010_alter_app_icon_appcontainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='computers',
            field=models.ManyToManyField(to='inventory.computergroup'),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.FileField(upload_to='static/files/2023-06-13_12-03-12'),
        ),
    ]
