# Generated by Django 4.1.6 on 2023-06-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0011_app_computers_alter_app_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='computers',
        ),
        migrations.AddField(
            model_name='app',
            name='containers',
            field=models.ManyToManyField(to='appscenter.appcontainer'),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.FileField(upload_to='static/files/2023-06-13_12-04-31'),
        ),
    ]
