# Generated by Django 4.1.6 on 2023-06-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0012_remove_app_computers_app_containers_alter_app_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.FileField(upload_to='static/files/2023-06-13_14-55-28'),
        ),
    ]
