# Generated by Django 4.1.6 on 2023-06-21 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0015_alter_app_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='icon',
        ),
        migrations.AddField(
            model_name='app',
            name='file',
            field=models.FileField(default=datetime.datetime(2023, 6, 21, 17, 28, 14, 594521, tzinfo=datetime.timezone.utc), upload_to='static/files/2023-06-21_17-28-02'),
            preserve_default=False,
        ),
    ]
