# Generated by Django 4.1.6 on 2023-07-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0027_appassign_last_breath_alter_app_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='file',
            field=models.FileField(upload_to='static/files/2023-07-20_04-58-45'),
        ),
    ]
